version: "3"

services:
  chakuraui:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/ChakuraUI
    tty: true
    ports:
      - 5173:5173
    container_name: chakuraui
